version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 55555
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"
    networks:
      - grocery_network

  grocery-service:
    build: ./grosery-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/grocery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 55555
    networks:
      - grocery_network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - grocery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/grocery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 55555
    networks:
      - grocery_network

networks:
  grocery_network:
    driver: bridge